### ISSUE TITLE
Year

### ISSUE THREAD

**Issue by nanhung** [liao961120/pttR#1]
Hi Yongfu,

很有趣的package，但我發現在使用`index2df()`時，似乎無法抓下年份的資訊，有辦法新增這個功能嗎？這樣或許在時間顯示上會比較完整。

**Comment by liao961120** [comment]
抱歉，先前未 watch 這個 repo 所以現在才回覆。

由於 `index2df()` 是抓取 PTT 文章列表 (e.g. [八卦版文章列表](https://www.ptt.cc/bbs/Gossiping/index.html)) 的資料 (下圖)。文章列表本身並沒有年份的資訊，所以無法抓取年份資料。

![ptt](https://user-images.githubusercontent.com/32927002/53332852-47102f80-392f-11e9-805f-9c1e5ba54255.png)

**Comment by nanhung** [comment]
OK, Thanks!
