### ISSUE TITLE
index2df() new argument based on articles' thumb scores

### ISSUE THREAD

**Issue by Dennishi0925** [liao961120/pttR#2]
Dear Yongfu,
感謝你的package, 想請問一下 ```index2df() ``` 是否有機會加上以推噓文數作為搜尋標準的argument, 謝謝!

**Comment by liao961120** [comment]
`index2df()` 的搜尋功能與 PTT 網頁版中的 "搜尋文章..." 等價 (基本上是幫使用者把搜尋關鍵字轉寫進 URL)

我不知道 PTT 網頁版本身有無提供推噓文數搜尋的功能 (但作者就有，所以可以用作者搜尋)。如果有的話，那實做應該不是問題。但我猜應該沒有。

![Screenshot from 2019-03-11 14-34-57](https://user-images.githubusercontent.com/32927002/54104434-e0991000-440a-11e9-8ac8-d7034fc5a76d.png)

**Comment by Dennishi0925** [comment]
網頁版搜尋確實沒辦法用推噓文，我自己在爬的時候是先抓文章列表下來自己filter再去爬符合條件的文章，因為用```index2df() ```可以省去抓太多文章列表花去的時間，所以才會想說是否有可能加入這個條件，還是謝謝你！
